tasks:
  - name: Install Waypoint
    command: |
      brew tap hashicorp/tap && \
      brew install hashicorp/tap/waypoint && \
      gp sync-done waypoint
  - name: Install doctl
    command: |
      gp sync-await waypoint && \
      brew install doctl && \
      doctl auth init --access-token $DIGITALOCEAN_ACCESS_TOKEN
      gp-sync doctl
  - name: Install kubectl
    command: brew install kubectl    
vscode:
  extensions:
    - hashicorp.terraform
    - ms-kubernetes-tools.vscode-kubernetes-tools
github:
  prebuilds:
    master: true
    pullRequests: true
    addComment: true  